### ISSUE TITLE
Adding few shot example for language generation

### ISSUE THREAD

**Issue by titipata** [PyThaiNLP/padthai#4]
@wannaphong maybe good to add an example for training language generation in the notebook?

**Comment by wannaphong** [comment]
Are you mean Text Generation?

**Comment by titipata** [comment]
Yes, I think adding a text generation script to `notebooks` with few-shot learning would be a good example.

**Comment by wannaphong** [comment]
OK, I added a text generation notebook.

https://github.com/PyThaiNLP/padthai/blob/main/notebooks/text_generation.ipynb

**Comment by titipata** [comment]
Looks great! Close this issue!
